package model;
// Generated 15/08/2016 08:49:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name="marca"
    ,schema="public"
)
public class Marca  implements java.io.Serializable {


     private int id_marca;
     private String nombre;
     private Set productos = new HashSet(0);

    public Marca(String nombre, int id_marca) {
        this.id_marca =id_marca;
        this.nombre = nombre;        
    }

	
    public Marca(int id_marca, String nombre) {
        this.id_marca = id_marca;
        this.nombre = nombre;
    }
    public Marca(int id_marca, String nombre, Set productos) {
       this.id_marca = id_marca;
       this.nombre = nombre;
       this.productos = productos;
    }
   
     @Id 

    
    @Column(name="id_marca", unique=true, nullable=false)
    public int getId_marca() {
        return this.id_marca;
    }
    
    public void setId_marca(int id_marca) {
        this.id_marca = id_marca;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="marca")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    @Override
    public String toString() {
        return nombre;
    }



}


