package model;
// Generated 15/08/2016 08:49:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,schema="public"
)
public class Producto  implements java.io.Serializable {


     private int codprodu;
     private Tipo tipo;
     private String nomprodu;
     private int costo;
     private int venta;
     private int ventaM;
     private int stock;
     private int promocion;
     private int historial;
     private int ventaC;
     private double porVen;
     private String unidadMedida;
     private int cantPaquete;     
     private double iva;
     private String estante;
     private double descuento;
     private Set detventas = new HashSet(0);
     private Set salidaPros = new HashSet(0);
     private Set detcompras = new HashSet(0);

    public Producto() {
        this.codprodu = 0;        
    }

	
    public Producto(int codprodu, Tipo tipo, String nomprodu, int costo, int venta, int ventaM, int stock, int promocion, int historial, int ventaC, double porVen, String unidadMedida, Integer cantPaquete, double iva, String estante, double descuento) {
        this.codprodu = codprodu;
        this.tipo = tipo;
        this.nomprodu = nomprodu;
        this.costo = costo;
        this.venta = venta;
        this.ventaM = ventaM;
        this.stock = stock;
        this.promocion = promocion;
        this.historial = historial;
        this.ventaC = ventaC;
        this.porVen = porVen;
        this.unidadMedida = unidadMedida;
        this.cantPaquete = cantPaquete;
        this.iva = iva;
        this.estante = estante;
        this.descuento = descuento;
    }
    public Producto(int codprodu, Tipo tipo, String nomprodu, int costo, int venta, int ventaM, int stock, int promocion, int historial, int ventaC, double porVen, String unidadMedida, Integer cantPaquete, double iva, String estante, double descuento, Set detventas, Set salidaPros, Set detcompras) {
        this.codprodu = codprodu;
        this.tipo = tipo;
        this.nomprodu = nomprodu;
        this.costo = costo;
        this.venta = venta;
        this.ventaM = ventaM;
        this.stock = stock;
        this.promocion = promocion;
        this.historial = historial;
        this.ventaC = ventaC;
        this.porVen = porVen;
        this.unidadMedida = unidadMedida;
        this.cantPaquete = cantPaquete;
        this.iva = iva;
        this.estante = estante;
        this.descuento = descuento;
        this.detventas = detventas;
        this.salidaPros = salidaPros;
        this.detcompras = detcompras;
    }
   
     @Id 

    
    @Column(name="codprodu", unique=true, nullable=false)
    public int getCodprodu() {
        return this.codprodu;
    }
    
    public void setCodprodu(int codprodu) {
        this.codprodu = codprodu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_id", nullable=false)
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="nomprodu", nullable=false, length=70)
    public String getNomprodu() {
        return this.nomprodu;
    }
    
    public void setNomprodu(String nomprodu) {
        this.nomprodu = nomprodu;
    }

    
    @Column(name="costo", nullable=false)
    public int getCosto() {
        return this.costo;
    }
    
    public void setCosto(int costo) {
        this.costo = costo;
    }

    
    @Column(name="venta", nullable=false)
    public int getPrecio1() {
        return this.venta;
    }
    
    public void setVenta(int venta) {
        this.venta = venta;
    }

    
    @Column(name="venta_m", nullable=false)
    public int getVentaM() {
        return this.ventaM;
    }
    
    public void setVentaM(int ventaM) {
        this.ventaM = ventaM;
    }

    
    @Column(name="stock", nullable=false)
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }

    
    @Column(name="promocion", nullable=false)
    public int getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(int promocion) {
        this.promocion = promocion;
    }

    
    @Column(name="historial", nullable=false)
    public int getHistorial() {
        return this.historial;
    }
    
    public void setHistorial(int historial) {
        this.historial = historial;
    }

    
    @Column(name="venta_c", nullable=false)
    public int getMonto() {
        return this.ventaC;
    }
    
    public void setVentaC(int ventaC) {
        this.ventaC = ventaC;
    }

    
    @Column(name="por_ven", nullable=false, precision=17, scale=17)
    public double getPorVen() {
        return this.porVen;
    }
    
    public void setPorVen(double porVen) {
        this.porVen = porVen;
    }
    @Column(name="unidad_medida", nullable=false, length=10)
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    @Column(name="cant_paquete", nullable=false)
    public int getCantPaquete() {
        return this.cantPaquete;
    }
    
    public void setCantPaquete(int cantPaquete) {
        this.cantPaquete = cantPaquete;
    }
    @Column(name="iva", nullable=false, precision=17, scale=17)
    public double getIva() {
        return this.porVen;
    }
    
    public void setIva(double iva) {
        this.iva = iva;
    }
    @Column(name="estante", nullable=false, length=10)
    public String getEstante() {
        return this.estante;
    }
    
    public void setEstante(String estante) {
        this.estante = estante;
    }
    @Column(name="descuento", nullable=false, precision=17, scale=17)
    public double getDescuento() {
        return this.porVen;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getDetventas() {
        return this.detventas;
    }
    
    public void setDetventas(Set detventas) {
        this.detventas = detventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getSalidaPros() {
        return this.salidaPros;
    }
    
    public void setSalidaPros(Set salidaPros) {
        this.salidaPros = salidaPros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getDetcompras() {
        return this.detcompras;
    }
    
    public void setDetcompras(Set detcompras) {
        this.detcompras = detcompras;
    }




}


