package model;
// Generated 15/08/2016 08:49:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name="tipo"
    ,schema="public"
)
public class reporte  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String impresora;
     private Set productos = new HashSet(0);

    public reporte(String nombre, int id) {
        this.id =id;
        this.nombre = nombre; 
        this.impresora = impresora;
    }

	
    public reporte(int id, String nombre, String impresora) {
        this.id = id;
        this.nombre = nombre;
        this.impresora = impresora;        
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    @Column(name="impresora", nullable=false, length=60)
    public String getImpresora() {
        return this.nombre;
    }
    
    public void setImpresora(String impresora) {
        this.impresora = impresora;
    }

    @Override
    public String toString() {
        return nombre;
    }
}


