package model;
// Generated 15/08/2016 08:49:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name="tipo"
    ,schema="public"
)
public class Tipo  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set productos = new HashSet(0);

    public Tipo(String nombre, int id) {
        this.id =id;
        this.nombre = nombre;        
    }

	
    public Tipo(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Tipo(int id, String nombre, Set productos) {
       this.id = id;
       this.nombre = nombre;
       this.productos = productos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipo")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    @Override
    public String toString() {
        return nombre;
    }



}


