package model;
// Generated 15/08/2016 08:49:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="vendedor"
    ,schema="public"
)
public class Vendedor  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private String ci;
     private String bloqueo;
     private double porciento;
     private String telefono;
     private double salario;
     private String observaciones;
     private Set ventas = new HashSet(0);

    public Vendedor() {
        this.id = 0;
    }

	
    public Vendedor(int id, String nombre, String apellido, String ci, String bloqueo, double porciento, String telefono, double salario, String observaciones) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.ci = ci;
        this.bloqueo = bloqueo;
        this.porciento = porciento;
        this.telefono = telefono;
        this.salario = salario;
        this.observaciones = observaciones;
    }
    public Vendedor(int id, String nombre, String apellido, String ci, String bloqueo, double porciento,String telefono, double salario, String observaciones, Set ventas) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.ci = ci;
       this.bloqueo = bloqueo;
       this.porciento = porciento;
       this.telefono = telefono;
       this.salario = salario;
       this.observaciones = observaciones;
       this.ventas = ventas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=70)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="ci", nullable=false, length=30)
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }

    
    @Column(name="bloqueo", nullable=false, length=20)
    public String getBloqueo() {
        return this.bloqueo;
    }
    
    public void setBloqueo(String bloqueo) {
        this.bloqueo = bloqueo;
    }

    
    @Column(name="porciento", nullable=false, precision=17, scale=17)
    public double getPorciento() {
        return this.porciento;
    }
    
    public void setPorciento(double porciento) {
        this.porciento = porciento;
    }
    @Column(name="telefono", nullable=false, length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    @Column(name="observaciones", nullable=false, length=100)
    public String getObservaciones() {
        return this.observaciones;
    }
    @Column(name="salario", nullable=false, precision=17, scale=17)
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="vendedor")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

    @Override
    public String toString() {
        return nombre;
    }


}


