/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;

import claseConectar.conectar;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
    public class cargarpago1 extends JDialog {

    /**
     * Creates new form cargarprov
     */
    Integer ban;    
    DefaultTableModel model;
    DefaultTableModel modeloRefresca;
    String saldoFijo;
    String codigoventa;
    String nroventas, montoventas, montosaldo;
    Integer codigocliente;
    Integer usuarioactu, idextracto, deuda;
    public cargarpago1(menu menuprincipal, boolean modal, Integer band, Integer usuario) {
        super(menuprincipal, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cod.setEnabled(false);
        usuarioactu=usuario;
        limpiar();
        autonumerar();
        calendar.setDate(new Date());
        this.ban = band;
        descrip.setDocument(new solomayusculas());
        this.setTitle("Nuevo Pago.");
        //btnventas.setEnabled(false);
    }
    private void autonumerar(){
            String sql="SELECT coalesce (max(idpago+1),1) as newid from pago";
            conectar cc = new conectar();
            Connection cn = cc.conexion(); 
        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);       
            rs.next();
            cod.setText(rs.getString("newid"));
            
        }catch(SQLException ex){
        
        }
    }
        private void autonumerarextracto(){
            String sql="SELECT coalesce (max(id_extracto+1),1) as newid from extracto";
            conectar cc = new conectar();
            Connection cn = cc.conexion(); 
        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);       
            rs.next();
            idextracto=Integer.parseInt(rs.getString("newid"));
            
        }catch(SQLException ex){
        
        }
    }
    
    void limpiar(){
        //nrofactura.setText("");
        //montofactura.setText("0");
        saldo.setText("0");
        pagar.setText("0");
        pagar.selectAll();
        //montofactura.setHorizontalAlignment(JTextField.RIGHT);
        saldo.setHorizontalAlignment(JTextField.RIGHT);
        pagar.setHorizontalAlignment(JTextField.RIGHT);
        descrip.setText("");
        //vuelto.setHorizontalAlignment(JTextField.RIGHT);
        //ruc.setText("");
        //telefono.setText("");          
        //direccion.setText("");
    }
    public void setModel(DefaultTableModel modelo){
        modelo = model;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        pagar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        calendar = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        descrip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        btncliente = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                // Forzamos un repintado apenas la ventana termina de abrirse: en algunos
                // entornos (drivers de video/D3D en Windows) el primer pintado de los
                // componentes estilizados no se completa hasta que ocurre un repintado
                // adicional, y esto evita depender de que el usuario pase el mouse encima.
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        getContentPane().revalidate();
                        getContentPane().repaint();
                    }
                });
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("COD.:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 30, 50, -1));

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 30));

        btnguardar.setBackground(new java.awt.Color(0, 102, 153));
        btnguardar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(240, 240, 240));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save3.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        btnguardar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnguardarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnguardarFocusLost(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 130, 40));

        btncancelar.setBackground(new java.awt.Color(0, 102, 153));
        btncancelar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(240, 240, 240));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        btncancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btncancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btncancelarFocusLost(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 120, 40));

        pagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pagar.setForeground(new java.awt.Color(255, 51, 0));
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });
        pagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pagarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pagarKeyTyped(evt);
            }
        });
        getContentPane().add(pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 260, 30));

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("MONTO PAGAR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 30));

        jLabel6.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("SALDO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        saldo.setEditable(false);
        saldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saldo.setForeground(new java.awt.Color(255, 51, 0));
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, 30));
        getContentPane().add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, 30));

        jLabel13.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("FECHA:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 60, 30));

        jLabel7.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("DESCRIPCION:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 30));

        descrip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripActionPerformed(evt);
            }
        });
        descrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripKeyReleased(evt);
            }
        });
        getContentPane().add(descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 260, 30));

        jLabel8.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("CLIENTE:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 30));

        cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, 30));

        btncliente.setBackground(new java.awt.Color(0, 102, 153));
        btncliente.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btncliente.setForeground(new java.awt.Color(240, 240, 240));
        btncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btncliente.setText("Seleccionar");
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });
        btncliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnclienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnclienteFocusLost(evt);
            }
        });
        getContentPane().add(btncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 130, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menusys.png"))); // NOI18N
        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        //ban = p.pasar(ban);
        System.out.print("valor bandera");
        System.out.print(ban);
        String sql="", sql1="";       
        Integer idusu;
        Integer idrol;        
        DecimalFormat formateador = new DecimalFormat("###,###");
        Integer aux=0, aux1=0, aux2, auxsaldo=0;
        String compa1=descrip.getText();
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        try{
            Number num = formateador.parse(pagar.getText());
            aux = num.intValue();
            Number num1 = formateador.parse(saldo.getText());
            aux1 = num1.intValue();
            auxsaldo=num.intValue();
            }catch (ParseException e){

            }
        System.out.print("   saldo    ");
        System.out.print(auxsaldo);
        System.out.print("   descripo    ");
        System.out.print(compa1);
        String sql5, sql6, sql8, sql9;
        if(auxsaldo>0 && !compa1.equals("")){
        try{          
                    System.out.print("     entra acaaaa    2   ");                                    
                    sql5 ="INSERT INTO pago (fecha, retraso, monto, saldo, descripcion, idpago, usuario, caja, cliente) VALUES ('"+calendar.getDate()+ "','0','"+aux+"','"+auxsaldo+"','"+descrip.getText()+"','"+cod.getText()+"','"+usuarioactu+"','1','"+codigocliente+"')";                                                        
                    PreparedStatement st6= cn.prepareStatement(sql5);                             
                    System.out.print(sql5);
                    System.out.print(st6);
                    //bloquear();        
                    String valor="";
                    //limpiar();                    
                    if(st6.executeUpdate()>0){
                        autonumerarextracto();
                        sql9 ="INSERT INTO extracto (id_extracto, activo, pasivo, saldo, idaux, usuario, caja, cliente, desripcion, fecha) VALUES ('"+idextracto+ "','"+aux+"','0','"+auxsaldo+"','"+cod.getText()+"','"+usuarioactu+"','1','"+codigocliente+"','"+descrip.getText()+"','"+calendar.getDate()+"')";                                                        
                        PreparedStatement st9= cn.prepareStatement(sql9);                             
                        System.out.print(sql9);
                        System.out.print(st9);     
                        System.out.print("     ANTES DEL PASIVO   ");
                        if(st9.executeUpdate()>0){
                            System.out.print("     PASIVO DEL EXTRACTO    ");
                            JOptionPane.showMessageDialog(null, "Se cargo exitosamente el Pago.");  
                            System.out.print("     HAY UN NULL QUE NO SE QUE ONDA    ");
                        }
                        //st9.close();
                        
                    }                    
                    //p.cargar(valor);                          
                    //st6.close(); 
                    System.out.print("     HAY UN NULL QUE NO SE QUE ONDA    ");
                    cargar("");
                    this.dispose();
        }catch(SQLException ex){            
        }
        }else{
            JOptionPane.showMessageDialog(null, "El pago debe ser mayor a 0 o Debe agregar una descripcion.");   
        }
    }//GEN-LAST:event_btnguardarActionPerformed
 
    void cargar(String valor){
        System.out.print("     ACA EMPIEZA EL PROBLEMA   ");
        String [] titulos ={"Cod","Nombre","Nro. Facturas","Total Deuda"};
        String [] registros = new String[4];
        String sql, sql1;
            sql="SELECT * FROM cliente ORDER BY nombre";
            System.out.print("entra en el simple");
               
//        modelRefresca = new DefaultTableModel (null, titulos){
//        @Override
//        public boolean isCellEditable(int row, int col)
//        {
//            return false;
//        }
//        };        
        try{
                conectar cc = new conectar();
                Connection cn = cc.conexion(); 
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                System.out.print(sql);
                Integer conta=0, montopasivo=0,montoactivo=0,diferencia=0, contasaldo=0;            
                DecimalFormat formateador = new DecimalFormat("###,###");
                model = new DefaultTableModel (null, titulos); 
                while(rs.next()){                    
                    sql1="SELECT * FROM extracto v where v.cliente='"+rs.getString("id")+"'";
                    System.out.print(sql1);
                    Statement st1 = cn.createStatement();
                    ResultSet as = st1.executeQuery(sql1);
                    while(as.next()){
                        conta=conta+1;                       
                        montopasivo=montopasivo+Integer.parseInt(as.getString("pasivo"));
                        montoactivo=montoactivo+Integer.parseInt(as.getString("activo"));
                        System.out.print("   hola     ");
                    }
                    diferencia=montoactivo-montopasivo;
                    if(diferencia<0){
                        System.out.print("    INGRESA PARA AGREGAR AL CLIENTE  ");
                        System.out.print("    EL ID DEL CLIENTE  ");
                        System.out.print(rs.getString("id"));
                        registros[0] = rs.getString("id");
                        registros[1] = rs.getString("nombre")+" "+rs.getString("apellido");
                        System.out.print("    EL NOMBRE DEL CLIENTE  ");
                        System.out.print(registros[1]);
                        registros[2] = formateador.format(diferencia);
                        System.out.print("    LA DIFERENCIA  ");
                        System.out.print(diferencia);
                        registros[3] = formateador.format(diferencia);
                        contasaldo=contasaldo+diferencia;
                        model.addRow(registros);
                    }
                    montopasivo=0;
                    montoactivo=0; 
                    diferencia=0;
                }
                model.fireTableDataChanged(); 
                deuda=contasaldo;
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "");
        } 
    }
    
    void abrircliente(){
    buscarcli p;
        menu mimenu;
        mimenu = new menu(0);
        p = new buscarcli(mimenu, true);
        p.setVisible(true);        
        DecimalFormat formateador = new DecimalFormat("###,###");
        if(p.codid!=null){
            
            codigocliente=Integer.parseInt(p.codid);
            System.out.print("     ESTE ES EL CODIGO DEL CLIENTE en el primero   ");
            System.out.print(codigocliente);
            cliente.setText(p.nombrecliente);
            String sql, sql1;
            sql="SELECT * FROM cliente where id='"+codigocliente+"'";
            System.out.print("entra en el simple");
            try{
                conectar cc = new conectar();
                Connection cn = cc.conexion(); 
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                System.out.print(sql);
                Integer conta=0, montopasivo=0,montoactivo=0,diferencia=0, contasaldo=0;            
                while(rs.next()){                                         
                    sql1="SELECT * FROM extracto v where v.cliente='"+rs.getString("id")+"'";
                    System.out.print(sql1);
                    Statement st1 = cn.createStatement();
                    ResultSet as = st1.executeQuery(sql1);
                    while(as.next()){
                        conta=conta+1;                       
                        montopasivo=montopasivo+Integer.parseInt(as.getString("pasivo"));
                        montoactivo=montoactivo+Integer.parseInt(as.getString("activo"));
                        System.out.print("   hola     ");
                    }
                    diferencia=montoactivo-montopasivo;
                    if(diferencia>=0){
                        JOptionPane.showMessageDialog(null, "El Cliente seleccionado no cuenta con deuda.");
                        pagar.setEnabled(false);
                        descrip.setEnabled(false);
                        btnguardar.setEnabled(false);
                        btncancelar.setEnabled(false);
                    }else{
                        diferencia=diferencia*-1;
                        pagar.setEnabled(true);
                        descrip.setEnabled(true);
                        btnguardar.setEnabled(true);
                        btncancelar.setEnabled(true);
                        pagar.requestFocus();
                        pagar.selectAll();
                    }
                    saldoFijo=diferencia.toString();
                    saldo.setText(formateador.format(diferencia));
                    montopasivo=0;
                    montoactivo=0; 
                    diferencia=0;
                }                
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "");
        } 
            //btnventas.setEnabled(true);
            //cargarprov(aux);
    }
}
    void abrirventa(){
    buscarventas2 p;
        menu mimenu;
        mimenu = new menu(0);
        System.out.print("     ESTE ES EL CODIGO DEL CLIENTE en el segundo   ");
            System.out.print(codigocliente);
        p = new buscarventas2(mimenu, true, codigocliente);
        p.setVisible(true);        
        DecimalFormat formateador = new DecimalFormat("###,###");
        
        if(p.codid!=null){
            try{
            String aux;
            codigoventa=p.codid;
            aux = p.codid;
            Number monto1 = formateador.parse(p.montofactura);
            Number monto2 = formateador.parse(p.saldo);
            //nrofactura.setText(p.fcliente);
            //montofactura.setText(formateador.format(monto1));
            saldo.setText(formateador.format(monto2));
            saldoFijo =monto2.toString();
            pagar.requestFocus();
            pagar.selectAll();
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
            }  
            
            //cargarprov(aux);
    }
    }
    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagarActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void pagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagarKeyReleased
        DecimalFormat formateador = new DecimalFormat("###,###");
        String aux;        
        Integer monto1, monto2, monto3=0, monto4=0, monto5=0;
        try {
            aux = pagar.getText();
            Number c = formateador.parse(aux);
            monto4 = c.intValue();
            pagar.setText(formateador.format(monto4));
            System.out.print(saldoFijo);
            System.out.print("    ESTE ES EL SALDO FIJO   ");
            Number d = formateador.parse(saldoFijo); 
            monto5 = d.intValue();
//            Number a = formateador.parse(saldo.getText());
//            monto1 = a.intValue();
//            Number b = formateador.parse(pagar.getText());
//            monto2 = b.intValue();
//            Number d = formateador.parse(saldoFijo);
//            monto5 = d.intValue();
//            System.out.print("    el  1   ");
//            //monto2=monto2+1;
            if(monto4>monto5){
                JOptionPane.showMessageDialog(null, "El pago debe ser menor o igual al saldo."); 
                pagar.setText("0");
            }
            
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
        }                                
        
    }//GEN-LAST:event_pagarKeyReleased

    private void descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripActionPerformed

    private void descripKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_descripKeyReleased

    private void pagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagarKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_pagarKeyTyped

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        abrircliente();
    }//GEN-LAST:event_btnclienteActionPerformed

    private void btnclienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnclienteFocusGained
        btncliente.setBackground(Color.red);
    }//GEN-LAST:event_btnclienteFocusGained

    private void btnclienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnclienteFocusLost
        btncliente.setBackground(new java.awt.Color(0,102,153));
    }//GEN-LAST:event_btnclienteFocusLost

    private void btnguardarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnguardarFocusGained
        btnguardar.setBackground(Color.red);
    }//GEN-LAST:event_btnguardarFocusGained

    private void btnguardarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnguardarFocusLost
        btnguardar.setBackground(new java.awt.Color(0,102,153));
    }//GEN-LAST:event_btnguardarFocusLost

    private void btncancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btncancelarFocusGained
        btncancelar.setBackground(Color.red);
    }//GEN-LAST:event_btncancelarFocusGained

    private void btncancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btncancelarFocusLost
        btncancelar.setBackground(new java.awt.Color(0,102,153));
    }//GEN-LAST:event_btncancelarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new cargarprov().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnguardar;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField descrip;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField pagar;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
