/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;

import claseConectar.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import model.reporte;

/**
 *
 * @author Usuario
 */
    public class cargarreporte extends JDialog {

    /**
     * Creates new form cargarprov
     */
    Integer ban;    
    DefaultTableModel model;
    DefaultTableModel modeloRefresca;
    public cargarreporte(menu menuprincipal, boolean modal) {
        super(menuprincipal, modal);
        initComponents();
        this.setLocationRelativeTo(null);
         this.setTitle("Modificar Impresora");
         cargartipo();
         cargarimpresora();
    }
void cargartipo(){
                String [] tipo = new String[2];
                conectar cc = new conectar();
                Connection cn = cc.conexion(); 
                String sql="SELECT * FROM reporte";
                DefaultComboBoxModel value;
                //Tipo ti= new Tipo();
                try{
                        Statement st = cn.createStatement();
                        ResultSet rs = st.executeQuery(sql);
                        comboreporte.removeAllItems();
                        //value =new DefaultComboBoxModel();
                        //combotipo.setModel(value);
                        while(rs.next()){
                            tipo[0] = rs.getString("id");
                            tipo[1] = rs.getString("nombre");         
                            Integer id=0;
                            id =Integer.parseInt(rs.getString("id"));
                            reporte tio = new reporte(rs.getString("nombre"), id);
                            comboreporte.addItem(new reporte(rs.getString("nombre"), id));                       
                        }
                }catch(SQLException ex){
                                JOptionPane.showMessageDialog(null, "");
                } 
    }
void cargarimpresora(){

                        DefaultComboBoxModel value;
                        //Tipo ti= new Tipo();
                        comboimpresora.removeAllItems();
                        //value =new DefaultComboBoxModel();
                        //combotipo.setModel(value);
                        int selectedService = 0;
                         Integer con=0;
                        PrintService[] services = PrintServiceLookup.lookupPrintServices(null, null);
                        for(int i = 0; i < services.length;i++){                                    
                                con=con+1;                                
                                comboimpresora.addItem(services[i].getName().toUpperCase());
                                System.out.print(services[i].getName().toUpperCase());                                
                        }                        
                        
    }
    void limpiar(){
        //ruc.setText("");
        //telefono.setText("");          
        //direccion.setText("");
    }
    public void setModel(DefaultTableModel modelo){
        modelo = modeloRefresca;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        comboimpresora = new javax.swing.JComboBox();
        comboreporte = new javax.swing.JComboBox();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("ELEGIR REPORTE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("ELEGIR IMPRESORA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, -1));

        btnguardar.setBackground(new java.awt.Color(0, 102, 153));
        btnguardar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(240, 240, 240));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save3.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 40));

        btncancelar.setBackground(new java.awt.Color(0, 102, 153));
        btncancelar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(240, 240, 240));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 120, 40));

        comboimpresora.setModel(new javax.swing.DefaultComboBoxModel());
        comboimpresora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboimpresoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboimpresoraFocusLost(evt);
            }
        });
        getContentPane().add(comboimpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, 30));

        comboreporte.setModel(new javax.swing.DefaultComboBoxModel());
        comboreporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboreporteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboreporteFocusLost(evt);
            }
        });
        getContentPane().add(comboreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menusys.png"))); // NOI18N
        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        String sql="";
        sql ="UPDATE reporte SET impresora='"+comboimpresora.getSelectedItem().toString()+"' where nombre='"+comboreporte.getSelectedItem().toString()+"'";         
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        try{        
        PreparedStatement st = cn.prepareStatement(sql);         
        st.executeUpdate();
        System.out.print(sql);       
        String valor="";                 
        if(st.executeUpdate()>0){
            JOptionPane.showMessageDialog(null, "Se guardo la impresora.");                                       
        }
        st.close(); 
        this.dispose();
        }catch(SQLException ex){            
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void comboimpresoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboimpresoraFocusGained

    }//GEN-LAST:event_comboimpresoraFocusGained

    private void comboimpresoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboimpresoraFocusLost
        comboimpresora.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_comboimpresoraFocusLost

    private void comboreporteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboreporteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_comboreporteFocusGained

    private void comboreporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboreporteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_comboreporteFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new cargarprov().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox comboimpresora;
    private javax.swing.JComboBox comboreporte;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
