/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;
import claseConectar.conectar;
import java.awt.Color;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UIManager;
import javax.swing.JMenuBar;
import java.awt.image.BufferedImage;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import java.awt.Color;
import java.awt.event.KeyEvent;
import org.jvnet.substance.skin.SubstanceDustLookAndFeel;
import org.jvnet.substance.skin.SubstanceTwilightLookAndFeel;
/**
 *
 * @author Usuario
 */
public class iniciosesion extends javax.swing.JFrame {
    private Connection connection = null;
    private ResultSet rs = null;
    private Statement s = null;
    public Integer idusuario;
    JMenuBar menusys1;
    JMenu sistema, Registros;
    JMenuItem Adminusu,exit;  
    public iniciosesion() {
//        menusys1 = new JMenuBar();
//        menusys1.setForeground(Color.BLUE);
//        menusys1.setBackground(Color.yellow);
        initComponents();        
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/ms.png")).getImage());
        ingresotext.setDocument(new solomayusculas());
        ingresopassword.setDocument(new solomayusculas());
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ingresotext = new javax.swing.JTextField();
        ingresopassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setForeground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("INICIAR SESION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 128, 31));

        jLabel2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("USUARIO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        jLabel3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        ingresotext.setBackground(new java.awt.Color(240, 240, 240));
        ingresotext.setCaretColor(new java.awt.Color(0, 102, 153));
        ingresotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresotextActionPerformed(evt);
            }
        });
        getContentPane().add(ingresotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 250, 43));

        ingresopassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresopasswordActionPerformed(evt);
            }
        });
        ingresopassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingresopasswordKeyPressed(evt);
            }
        });
        getContentPane().add(ingresopassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 250, 43));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("INGRESAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 135, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("CERRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 133, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letras.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 100, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1496628980_lock.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String usuario = ingresotext.getText();
        String pass = new String (ingresopassword.getPassword());
        if(usuario.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese Usuario");            
        }else{
            acceder(usuario, pass);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    void acceder(String usuario, String pass){
        String sql ="SELECT * FROM usuario WHERE usuario='"+usuario+"' and clave='"+pass+"'";
        String Usuario="";
        String Pass="";
        String rol ="";
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        try {            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);                                    
            while(rs.next()){
                Usuario =rs.getString("usuario");
                Pass = rs.getString("clave");   
                rol = rs.getString("rol_id");
                idusuario = Integer.parseInt(rs.getString("id"));
            }            
            if(Usuario.equals(usuario) && Pass.equals(pass)){
                if(rol.equals("0")){
                    System.out.print(Usuario);
                    System.out.print(rol);
                    System.out.print(" el usuario es ");
                    System.out.print(idusuario);
                    menu m = new menu(idusuario);
                    m.setVisible(true);
                    m.setTitle("Menú Principal.");
                    dispose();                
                }else{
                    System.out.print(Usuario);
                    System.out.print(rol);
                    menu2 m = new menu2(idusuario);
                    m.setVisible(true);
                    m.setTitle("Menú Principal.");
                    dispose(); 
                }
            }else{
                JOptionPane.showMessageDialog(this, "Usuario Incorrecto");
                ingresopassword.requestFocus();
                ingresopassword.selectAll();
            }            
            cn.close();
        } catch (SQLException ex) {
            Logger.getLogger(iniciosesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void ingresopasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresopasswordActionPerformed
        ingresopassword.transferFocus();
    }//GEN-LAST:event_ingresopasswordActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
                                    
    }//GEN-LAST:event_jButton1MouseClicked

    private void ingresotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresotextActionPerformed
        ingresotext.transferFocus();
    }//GEN-LAST:event_ingresotextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ingresopasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresopasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String usuario = ingresotext.getText();
            String pass = new String (ingresopassword.getPassword());
            if(usuario.equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese Usuario");            
            }else{
                acceder(usuario, pass);
            }
        }    
    }//GEN-LAST:event_ingresopasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.getLookAndFeelDefaults().put(
                    "JMenuBar[Enabled].textForeground", Color.RED);
                    javax.swing.UIManager.getLookAndFeelDefaults().put(
                    "JMenuBar[Enabled].textForeground", Color.RED);
                    javax.swing.UIManager.put("MenuBarUI.background", Color.GREEN);
//                    UIManager.setLookAndFeel(new SubstanceTwilightLookAndFeel());
//                    UIManager.setLookAndFeel("org.jvnet.substance.skin.SubstanceTwilightLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciosesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciosesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fondo;
    private javax.swing.JPasswordField ingresopassword;
    private javax.swing.JTextField ingresotext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
}
