/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;
import claseConectar.conectar;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.table.*;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.util.Date;
import java.sql.ResultSet;
//import org.apache.log4j.Logger;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;

/**
 *
 * @author Usuario
 */
public class presuaux extends JDialog {

    DefaultTableModel model;
    DefaultComboBoxModel modeloRol;
    Integer band=0, band1=0;
    String descrippro, preciopro;
    Integer idcosto;
    String tipoiva="";
    public presuaux(menu menuprincipal, boolean modal) {
        super(menuprincipal, modal);
        initComponents();        
        this.setLocation(400, 150);
        DecimalFormat formateador = new DecimalFormat("###,###");
        cod.requestFocus();
        monto.setHorizontalAlignment(JTextField.RIGHT);
        monto.setText("0");
        costo.setHorizontalAlignment(JTextField.RIGHT);
        costo.setText("0");
        cod.setDocument(new solomayusculas());
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboiva = new javax.swing.JComboBox();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                // Forzamos un repintado apenas la ventana termina de abrirse: en algunos
                // entornos (drivers de video/D3D en Windows) el primer pintado de los
                // componentes estilizados no se completa hasta que ocurre un repintado
                // adicional, y esto evita depender de que el usuario pase el mouse encima.
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        getContentPane().revalidate();
                        getContentPane().repaint();
                    }
                });
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 50));

        guardar.setBackground(new java.awt.Color(0, 102, 153));
        guardar.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        guardar.setForeground(new java.awt.Color(240, 240, 240));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save3.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        guardar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                guardarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                guardarFocusLost(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 130, -1));

        jLabel4.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("PRECIO DE VENTA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, 40));

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("INGRESAR DESCRIPCION DEL PRODUCTO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 40));

        cod.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        cod.setForeground(new java.awt.Color(255, 51, 0));
        cod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codFocusLost(evt);
            }
        });
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 40));

        monto.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        monto.setForeground(new java.awt.Color(255, 51, 0));
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        monto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                montoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                montoFocusLost(evt);
            }
        });
        monto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                montoPropertyChange(evt);
            }
        });
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                montoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoKeyTyped(evt);
            }
        });
        getContentPane().add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 190, 40));

        jLabel6.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("PRECIO DE COSTO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, 40));

        costo.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        costo.setForeground(new java.awt.Color(255, 51, 0));
        costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoActionPerformed(evt);
            }
        });
        costo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                costoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                costoFocusLost(evt);
            }
        });
        costo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                costoPropertyChange(evt);
            }
        });
        costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoKeyTyped(evt);
            }
        });
        getContentPane().add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 190, 40));

        jLabel7.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("PRECIO DE VENTA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, 40));

        comboiva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10%", "5%","Exenta"}));
        getContentPane().add(comboiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 70, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 220));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menusys.png"))); // NOI18N
        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
    }//GEN-LAST:event_formComponentHidden

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
//        menu m = menu.getInstance();
//        m.setEnabled(true);
//        m.show();
    }//GEN-LAST:event_formWindowIconified

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void montoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_montoPropertyChange
        monto.setHorizontalAlignment(4);
    }//GEN-LAST:event_montoPropertyChange

    private void montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_montoKeyTyped

    private void montoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyReleased
         DecimalFormat formateador = new DecimalFormat("###,###");
        String aux;        
        Integer monto1, monto2, monto3=0, monto4=0;
        try {
            aux = monto.getText();
            Number c = formateador.parse(aux);
            monto4 = c.intValue();
            monto.setText(formateador.format(monto4));
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
        }                                           
    }//GEN-LAST:event_montoKeyReleased

    private void montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(cod.getText().length()!=0){
                DecimalFormat formateador = new DecimalFormat("###,###");
                Integer aux1=0, aux3=0;
                String aux, aux2;
                try {
                    aux = monto.getText();
                    Number c = formateador.parse(aux);
                    aux1=c.intValue();
                    aux2 = costo.getText();
                    Number x = formateador.parse(aux2);
                    aux3=x.intValue();
                } catch (ParseException ex) {
                    java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
                } 
                if(aux1>0 && aux3>0){
                    descrippro = this.cod.getText();
                    //preciopro = this.monto.getText();
                    Integer totalaux1 = 0;
                    try{
                        Number num = formateador.parse(this.monto.getText());
                        totalaux1 = num.intValue();
                        }catch (ParseException e){
                    }
                    idcosto=aux3;
                    preciopro = totalaux1.toString();
                    this.dispose();
                    
                    }else{
                        JOptionPane.showMessageDialog(null, "Debe ingresar un precio costo y venta.");
                        monto.requestFocus();
                        monto.selectAll();
                    }
            }else{
                JOptionPane.showMessageDialog(null, "Tienes que agregar una descripcion.");
                cod.requestFocus();
            }
        }
    }//GEN-LAST:event_montoKeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        if(cod.getText().length()!=0){
                DecimalFormat formateador = new DecimalFormat("###,###");
                Integer aux1=0;
                String aux, auxx;
                
                try {
                    aux = monto.getText();
                    Number c = formateador.parse(aux);
                    aux1=c.intValue();
                    auxx = costo.getText();
                    Number x = formateador.parse(auxx);
                    idcosto=x.intValue();
                    tipoiva=comboiva.getSelectedItem().toString();
                } catch (ParseException ex) {
                    java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
                } 
                if(aux1>0){
                    if(idcosto>0){
                        if(aux1>idcosto){
                        descrippro = this.cod.getText();
                        //preciopro = this.monto.getText();
                        Integer totalaux1 = 0;
                        try{
                            Number num = formateador.parse(this.monto.getText());
                            totalaux1 = num.intValue();
                        }catch (ParseException e){
                        }
                            preciopro = totalaux1.toString();
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "El costo Debe ser inferior al precio de Venta.");
                            monto.requestFocus();
                            monto.selectAll();
                        }
                        }else{
                            JOptionPane.showMessageDialog(null, "Debe ingresar un precio de Costo.");
                            monto.requestFocus();
                            monto.selectAll();
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Debe ingresar un precio Unitario.");
                        monto.requestFocus();
                        monto.selectAll();
                    }
            }else{
                JOptionPane.showMessageDialog(null, "Tienes que agregar una descripcion.");
                cod.requestFocus();
            }        
    }//GEN-LAST:event_guardarActionPerformed

    private void costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoActionPerformed

    private void costoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_costoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_costoPropertyChange

    private void costoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoKeyPressed

    private void costoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyReleased
        DecimalFormat formateador = new DecimalFormat("###,###");
        String aux;        
        Integer monto1, monto2, monto3=0, monto4=0;
        try {
            aux = costo.getText();
            Number c = formateador.parse(aux);
            monto4 = c.intValue();
            costo.setText(formateador.format(monto4));
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_costoKeyReleased

    private void costoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_costoKeyTyped

    private void guardarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guardarFocusGained
        guardar.setBackground(Color.red);
    }//GEN-LAST:event_guardarFocusGained

    private void guardarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guardarFocusLost
        guardar.setBackground(new java.awt.Color(0,102,153));
    }//GEN-LAST:event_guardarFocusLost

    private void codFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codFocusGained
        cod.setBackground(Color.red);
        cod.setForeground(Color.WHITE);
    }//GEN-LAST:event_codFocusGained

    private void codFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codFocusLost
        cod.setForeground(new java.awt.Color(255,51,0));
        cod.setBackground(Color.WHITE);
    }//GEN-LAST:event_codFocusLost

    private void costoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costoFocusGained
        costo.setBackground(Color.red);
        costo.setForeground(Color.WHITE);
    }//GEN-LAST:event_costoFocusGained

    private void costoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costoFocusLost
        costo.setForeground(new java.awt.Color(255,51,0));
        costo.setBackground(Color.WHITE);
    }//GEN-LAST:event_costoFocusLost

    private void montoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montoFocusGained
        monto.setBackground(Color.red);
        monto.setForeground(Color.WHITE);
    }//GEN-LAST:event_montoFocusGained

    private void montoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montoFocusLost
        monto.setForeground(new java.awt.Color(255,51,0));
        monto.setBackground(Color.WHITE);
    }//GEN-LAST:event_montoFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new proveedor().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod;
    private javax.swing.JComboBox comboiva;
    private javax.swing.JTextField costo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField monto;
    // End of variables declaration//GEN-END:variables
}
