/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;
import claseConectar.conectar;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.table.*;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.util.Date;
import java.sql.ResultSet;
//import org.apache.log4j.Logger;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;

/**
 *
 * @author Usuario
 */
public class reajusteaux extends JDialog {

    DefaultTableModel model;
    DefaultComboBoxModel modeloRol;
    Integer band=0, band1=0;
    String descrippro; 
    Double stockpro;
    Integer idcosto;
    Integer idproducto, cantaux, montoaux, preuniaux;    
    Integer codigoaux;
    Integer usuarioactu;
    public reajusteaux(menu menuprincipal, boolean modal, Integer idprodu, Integer usuario) {
        super(menuprincipal, modal);
        initComponents();        
        this.setLocation(280, 150);
        DecimalFormat formateador = new DecimalFormat("###,###");
        cod.requestFocus();
        usuarioactu=usuario;
        monto.setHorizontalAlignment(JTextField.RIGHT);
        //monto.setText("0");
        costo.setHorizontalAlignment(JTextField.RIGHT);
        //costo.setText("0");
        cod.setEditable(false);
        idproducto=idprodu;
        costo.requestFocus();
        //costo.setText("1");
        //costo.selectAll();
        monto.setEditable(false);
        newstock.setEditable(false);
        cargar("");
    }        
    private void autonumerar(){
            String sql="SELECT coalesce (max(id+1),1) as newid from reajuste";
            conectar cc = new conectar();
            Connection cn = cc.conexion(); 
        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);       
            rs.next();
            codigoaux=Integer.parseInt(rs.getString("newid"));    
            cn.close();
        }catch(SQLException ex){
        
        }
    }
    void cargar(String valor){
        String [] titulos ={"Cod","Nombre","P. Costo","P. Venta", "Stock","Marca","Tipo"};
        String [] registros = new String[7];
        String sql, sql1, sql2;
        Double contador=0.0, sumacompra=0.0, sumaventa=0.0, aux1=0.0,aux2=0.0;
        System.out.print("    ESTE ES EL ID     ");
        System.out.print(idproducto);
        sql="SELECT * FROM producto WHERE codprodu='"+idproducto+"'";              
        model = new DefaultTableModel (null, titulos){
        @Override
        public boolean isCellEditable(int row, int col)
        {
            return false;
        }
        };                
        try{
                conectar cc = new conectar();
                Connection cn = cc.conexion(); 
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                System.out.print(sql);
                DecimalFormat formateador = new DecimalFormat("###,###");
                while(rs.next()){
                    cod.setText(rs.getString("nomprodu"));   
                    aux2=Double.parseDouble(rs.getString("stock"));
                    stockpro=Double.parseDouble(rs.getString("stock"));
                    monto.setText(formateador.format(aux2));
                    newstock.setText(formateador.format(aux2));
                }                
        cn.close();
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "");
        } 
//       view.setEnabled(false);
//       delete.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        newstock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combovendedor = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 970, 50));

        guardar.setBackground(new java.awt.Color(0, 102, 153));
        guardar.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        guardar.setForeground(new java.awt.Color(240, 240, 240));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save3.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 130, -1));

        jLabel4.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("STOCK ACTU:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, 40));

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("INGRESAR DESCRIPCION DEL PRODUCTO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 40));

        cod.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        cod.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 40));

        monto.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        monto.setForeground(new java.awt.Color(255, 51, 0));
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        monto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                montoPropertyChange(evt);
            }
        });
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                montoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoKeyTyped(evt);
            }
        });
        getContentPane().add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 140, 40));

        jLabel6.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("TIPO REAJUSTE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, 40));

        costo.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        costo.setForeground(new java.awt.Color(255, 51, 0));
        costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoActionPerformed(evt);
            }
        });
        costo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                costoPropertyChange(evt);
            }
        });
        costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoKeyTyped(evt);
            }
        });
        getContentPane().add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 160, 40));

        newstock.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        newstock.setForeground(new java.awt.Color(255, 51, 0));
        newstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newstockActionPerformed(evt);
            }
        });
        newstock.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                newstockPropertyChange(evt);
            }
        });
        newstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newstockKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newstockKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newstockKeyTyped(evt);
            }
        });
        getContentPane().add(newstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 140, 40));

        jLabel7.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("NUEVO STOCK:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, 40));

        combovendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suma", "Resta"}));
        combovendedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combovendedorItemStateChanged(evt);
            }
        });
        combovendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combovendedorActionPerformed(evt);
            }
        });
        combovendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combovendedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                combovendedorFocusLost(evt);
            }
        });
        getContentPane().add(combovendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 120, 40));

        jLabel8.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("CANTIDAD DE AJUSTE:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 220));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menusys.png"))); // NOI18N
        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
    }//GEN-LAST:event_formComponentHidden

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
//        menu m = menu.getInstance();
//        m.setEnabled(true);
//        m.show();
    }//GEN-LAST:event_formWindowIconified

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void montoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_montoPropertyChange
        monto.setHorizontalAlignment(4);
    }//GEN-LAST:event_montoPropertyChange

    private void montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_montoKeyTyped

    private void montoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyReleased
         DecimalFormat formateador = new DecimalFormat("###,###");
        String aux;        
        Integer monto1, monto2, monto3=0, monto4=0;
        try {
            aux = monto.getText();
            Number c = formateador.parse(aux);
            monto4 = c.intValue();
            monto.setText(formateador.format(monto4));
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
        }                                           
    }//GEN-LAST:event_montoKeyReleased

    private void montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyPressed
        
    }//GEN-LAST:event_montoKeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       
        Integer idusu;
        Integer idrol;        
        DecimalFormat formateador = new DecimalFormat("###,###");
        Integer aux=0, aux1=0, aux2, auxsaldo=0;
        System.out.print("   saldo    ");
        System.out.print(auxsaldo);
        System.out.print("   descripo    ");        
        Date mydate =new Date();
        autonumerar();
        if(!costo.getText().equals("")){
        try{        
                    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
                    Date date = new Date();
                    System.out.println("Hora actual: " + dateFormat.format(date));
                    String sql ="INSERT INTO reajuste (id, fecha, descripcion, producto_codprodu, estado, total, usuario, cantidad, hora) VALUES ('"+codigoaux+"','" +mydate+ "', ' ', '"+idproducto+"','"+combovendedor.getSelectedItem()+"','0','"+usuarioactu+"','"+costo.getText()+"','"+dateFormat.format(date)+"')";                                    
                    conectar cc = new conectar();
                    Connection cn = cc.conexion(); 
                    PreparedStatement st = cn.prepareStatement(sql);         
                    System.out.print(sql);
                    //bloquear();        
                    String valor="";
                    //limpiar();
                    if(st.executeUpdate()>0){                        
                        String sqlaux, sqlaux2;
                        Double stockaux=0.0, totalstock=0.0;
                        Double auxcanti=0.0;                        
                        //sqlaux="SELECT * FROM producto where codprodu='"+idproducto+"'";                       
                        try{
                            cn.createStatement();
//                            Statement st4 = cn.createStatement();
//                            ResultSet fs = st4.executeQuery(sqlaux);                                                        
//                            while(fs.next()){
//                                stockaux= Double.parseDouble(fs.getString("stock"));   
//                            }
//                            System.out.print("Cantidad de Stock");
//                            System.out.print(stockaux);
//                            //auxcanti = Double.parseDouble(montofactura.getText());
//                            totalstock = stockaux-Double.parseDouble(montofactura.getText());                        
                            String sql6 ="UPDATE producto SET stock='"+newstock.getText()+"' where codprodu='"+idproducto+"'";
                            PreparedStatement st6 = cn.prepareStatement(sql6);
                            if(st6.executeUpdate()>0){
                                JOptionPane.showMessageDialog(null, "Se realizó Correctamente el Reajuste.");
                            }else{
                                JOptionPane.showMessageDialog(null, "No se realizó el Reajuste.");
                            }
                        }catch(SQLException ex){   
                            JOptionPane.showMessageDialog(null, "DESCUENTO DE STOCK");
                        }                          
                    this.dispose();
                    //cargar("");
                    }
        cn.close();
        }catch(SQLException ex){            
        }
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero de Reajuste.");
            costo.requestFocus();
        }                
    }//GEN-LAST:event_guardarActionPerformed

    private void costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoActionPerformed

    private void costoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_costoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_costoPropertyChange

    private void costoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoKeyPressed

    private void costoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyReleased
        Double cantaux=0.0;
        Double precioaux=0.0;
        DecimalFormat formateador = new DecimalFormat("###,###");
        if(!costo.getText().equals("")){
            if(combovendedor.getSelectedItem().equals("Suma")){
                Double aux1 =0.0;
                try{
                    Number aux = formateador.parse(monto.getText());
                    aux1 = aux.doubleValue();
                }catch (ParseException e){

                }
                cantaux= Double.parseDouble(costo.getText());
                precioaux= aux1;   
                Double calculo=0.0;
                calculo= cantaux+stockpro;
                System.out.print("   el precio uni es    ");
                System.out.print(stockpro);
                newstock.setText(calculo.toString());    
            }else{
                Double aux1 =0.0;
                try{
                    Number aux = formateador.parse(monto.getText());
                    aux1 = aux.doubleValue();
                }catch (ParseException e){

                }
                cantaux= Double.parseDouble(costo.getText());
                precioaux= aux1;   
                Double calculo=0.0;
                calculo= stockpro-cantaux;
                System.out.print("   el precio uni es    ");
                System.out.print(stockpro);
                newstock.setText(calculo.toString()); 
            }    
        }else{
            newstock.setText(stockpro.toString());
        }
    }//GEN-LAST:event_costoKeyReleased

    private void costoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_costoKeyTyped

    private void newstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newstockActionPerformed

    private void newstockPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_newstockPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_newstockPropertyChange

    private void newstockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newstockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_newstockKeyPressed

    private void newstockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newstockKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_newstockKeyReleased

    private void newstockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newstockKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_newstockKeyTyped

    private void combovendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combovendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combovendedorActionPerformed

    private void combovendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combovendedorFocusGained
        combovendedor.setBackground(Color.red);
    }//GEN-LAST:event_combovendedorFocusGained

    private void combovendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combovendedorFocusLost
        combovendedor.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_combovendedorFocusLost

    private void combovendedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combovendedorItemStateChanged
        if(!costo.getText().equals("")){
            Double cantaux=0.0;
        Integer precioaux=0;
        DecimalFormat formateador = new DecimalFormat("###,###");
        if(combovendedor.getSelectedItem().toString().equals("Suma")){
            Integer aux1 =0;
                try{
                    Number aux = formateador.parse(monto.getText());
                    aux1 = aux.intValue();
                }catch (ParseException e){

                }
                cantaux= Double.parseDouble(costo.getText());
                precioaux= aux1;   
                Double calculo=0.0;
                calculo= cantaux+stockpro;
                System.out.print("   el precio uni es    ");
                System.out.print(stockpro);
                newstock.setText(formateador.format(calculo));
        }else{
            Integer aux1 =0;
                try{
                    Number aux = formateador.parse(monto.getText());
                    aux1 = aux.intValue();
                }catch (ParseException e){

                }
                cantaux= Double.parseDouble(costo.getText());
                precioaux= aux1;   
                Double calculo=0.0;
                calculo= stockpro-cantaux;
                System.out.print("   el precio uni es    ");
                System.out.print(stockpro);
                newstock.setText(formateador.format(calculo)); 
        }
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero.");
            costo.requestFocus();            
        }
        
    }//GEN-LAST:event_combovendedorItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new proveedor().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod;
    private javax.swing.JComboBox combovendedor;
    private javax.swing.JTextField costo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField newstock;
    // End of variables declaration//GEN-END:variables
}
