/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;

import claseConectar.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
    public class updatepago1 extends JDialog {

    /**
     * Creates new form cargarprov
     */
    Integer ban;    
    DefaultTableModel model;
    DefaultTableModel modeloRefresca;
    String saldoFijo;
    String codigoventa;
    String nroventas, montoventas, fcliente1;
    public updatepago1(menu menuprincipal, boolean modal, Integer band, String codigo, String fcliente) {
        super(menuprincipal, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cod.setEnabled(false);
        fcliente1 = fcliente;
        cargar(codigo);
        bloquear();
        descrip.setDocument(new solomayusculas());
        //limpiar();
        //autonumerar();
        //calendar.setDate(new Date());
        this.ban = band;
        this.setTitle("Modificar Pago.");
    }
    private void autonumerar(){
            String sql="SELECT coalesce (max(id_pago+1),1) as newid from pagos";
            conectar cc = new conectar();
            Connection cn = cc.conexion(); 
        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);       
            rs.next();
            cod.setText(rs.getString("newid"));
            
        }catch(SQLException ex){
        
        }
    }
    private void bloquear(){
        nrofactura.setEnabled(false);
        //montofactura.setEnabled(false);
        pagar.setEnabled(false);
        saldo.setEnabled(false);
        descrip.setEnabled(false);
        calendar.setEnabled(false);
        btnguardar1.setEnabled(false);
        btnmodificar.setEnabled(true);
    }
    private void desbloquear(){
        nrofactura.setEnabled(true);
        //montofactura.setEnabled(true);
        saldo.setEnabled(true);
        pagar.setEnabled(true);
        descrip.setEnabled(true);
        calendar.setEnabled(true);
        btnguardar1.setEnabled(true);
        btnmodificar.setEnabled(false);
        pagar.requestFocus();
        pagar.selectAll();
    }
    void limpiar(){
        nrofactura.setText("");
        //montofactura.setText("0");
        saldo.setText("0");
        pagar.setText("0");
        pagar.selectAll();
        //montofactura.setHorizontalAlignment(JTextField.RIGHT);
        saldo.setHorizontalAlignment(JTextField.RIGHT);
        pagar.setHorizontalAlignment(JTextField.RIGHT);
        descrip.setText("");
        //vuelto.setHorizontalAlignment(JTextField.RIGHT);
        //ruc.setText("");
        //telefono.setText("");          
        //direccion.setText("");
    }
    public void setModel(DefaultTableModel modelo){
        modelo = modeloRefresca;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nrofactura = new javax.swing.JTextField();
        btncancelar1 = new javax.swing.JButton();
        pagar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        calendar = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        descrip = new javax.swing.JTextField();
        btnguardar1 = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("COD.:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 30, 50, -1));

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 30));

        jLabel3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("CLIENTE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 30));

        nrofactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nrofactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrofacturaActionPerformed(evt);
            }
        });
        getContentPane().add(nrofactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, 30));

        btncancelar1.setBackground(new java.awt.Color(0, 102, 153));
        btncancelar1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btncancelar1.setForeground(new java.awt.Color(240, 240, 240));
        btncancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btncancelar1.setText("Seleccionar");
        btncancelar1.setEnabled(false);
        btncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 130, 30));

        pagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pagar.setForeground(new java.awt.Color(255, 51, 0));
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });
        pagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pagarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pagarKeyTyped(evt);
            }
        });
        getContentPane().add(pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("MONTO PAGAR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 30));

        jLabel6.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("SALDO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        saldo.setEditable(false);
        saldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saldo.setForeground(new java.awt.Color(255, 51, 0));
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 260, 30));
        getContentPane().add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, 30));

        jLabel13.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("FECHA:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 60, 30));

        jLabel7.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("DESCRIPCION:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 30));

        descrip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripActionPerformed(evt);
            }
        });
        descrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripKeyReleased(evt);
            }
        });
        getContentPane().add(descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 260, 30));

        btnguardar1.setBackground(new java.awt.Color(0, 102, 153));
        btnguardar1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnguardar1.setForeground(new java.awt.Color(240, 240, 240));
        btnguardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save3.png"))); // NOI18N
        btnguardar1.setText("Guardar");
        btnguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, 40));

        btnmodificar.setBackground(new java.awt.Color(0, 102, 153));
        btnmodificar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(240, 240, 240));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 130, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menusys.png"))); // NOI18N
        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void cargar(String valor){
        String [] titulos ={"Cod","Fecha","Cliente", "Descripcion" , "Total"};
        String [] registros = new String[5];
        String sql6="", sql7="", sql8="";
            sql6="SELECT * FROM pago where idpago='"+valor+"'ORDER BY idpago";
            System.out.print("entra en el simple");                      
        modeloRefresca = new DefaultTableModel (null, titulos);        
        try{
                conectar cc = new conectar();
                Connection cn = cc.conexion(); 
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql6);
                System.out.print(sql6);
                Integer conta=0, monto=0, contasaldo=0;            
                DecimalFormat formateador = new DecimalFormat("###,###");
                while(rs.next()){                    
                    cod.setText(rs.getString("idpago"));                    
                    calendar.setDate(rs.getDate("fecha")); 
                    descrip.setText(rs.getString("descripcion"));                         
                    pagar.setText(formateador.format(Integer.parseInt(rs.getString("monto"))));  
                    sql7="SELECT * FROM cliente where id='"+rs.getString("cliente")+"'";         
                    st = cn.createStatement();
                    ResultSet as = st.executeQuery(sql7);
                    Integer montopasivo=0,montoactivo=0,diferencia=0; 
                    while(as.next()){
                        nrofactura.setText(as.getString("nombre")+" "+as.getString("apellido"));
                        sql8="SELECT * FROM extracto v where v.cliente='"+as.getString("id")+"'";
                        System.out.print(sql8);
                        Statement st1 = cn.createStatement();
                        ResultSet xs = st1.executeQuery(sql8);
                        while(xs.next()){
                            //conta=conta+1;                       
                            montopasivo=montopasivo+Integer.parseInt(xs.getString("pasivo"));
                            montoactivo=montoactivo+Integer.parseInt(xs.getString("activo"));
                            System.out.print("   hola     ");
                        }
                    diferencia=montoactivo-montopasivo;
                    diferencia=diferencia*-1;
                    saldoFijo=diferencia.toString();
                    }
                    saldo.setText(formateador.format(diferencia));
                    modeloRefresca.addRow(registros);                                                                 
                }
                modeloRefresca.fireTableDataChanged();                               
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "");
        } 
       //view.setEnabled(false);
       //cargarcompra.setEnabled(false);
       //buscartxt.setEnabled(true);
    }
    void cargarpago(String valor){
        String [] titulos ={"Cod","Fecha","Descripcion","Codcli","Cliente", "Monto"};
        String [] registros = new String[6];
        String sql, sql1, sql2, sql3;
        if(valor.equals("")){
            sql="SELECT * FROM pago ORDER BY idpago";
            System.out.print("entra en el simple");
        }else{
            sql="SELECT * FROM pago p inner join cliente x on p.cliente=x.id where UPPER(x.nombre) LIKE UPPER('%"+valor+"%')  ORDER BY idpago";
            System.out.print("entra en el segundo");
        }                
        model = new DefaultTableModel (null, titulos){
        @Override
        public boolean isCellEditable(int row, int col)
        {
            return false;
        }
        };         
        try{
                conectar cc = new conectar();
                Connection cn = cc.conexion(); 
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                System.out.print(sql);
                String idventa="", idcliente="";
                DecimalFormat formateador = new DecimalFormat("###,###");
                while(rs.next()){
                    System.out.print("    ACA SI ENTRA    ");
                    registros[0] = rs.getString("idpago");
                    System.out.println("        Este es el id Pago    ");
                    System.out.println(rs.getString("idpago"));
                    registros[1] = rs.getString("fecha");
                    System.out.println("        Este es el fecha Pago    ");
                    System.out.println(rs.getString("fecha"));
                    registros[2] = rs.getString("descripcion");
                    System.out.println("        Este es el descrip Pago    ");
                    System.out.println(rs.getString("descripcion"));                     
                    sql3="SELECT * FROM cliente where id='"+rs.getString("cliente")+"'";
                    registros[3] =rs.getString("cliente");
                    System.out.print("   ESTE ES EL SQL   ");
                    System.out.print(sql3);
                    Statement st3 = cn.createStatement();
                    st3 = cn.createStatement();
                    ResultSet xs = st3.executeQuery(sql3);
                    while(xs.next()){                       
                        registros[4] = xs.getString("nombre")+" "+xs.getString("apellido");              
                        System.out.print("   ESTE ES EL CLIENTE   ");
                        System.out.print(registros[3]);
                    }
                    registros[5] = formateador.format(Integer.parseInt(rs.getString("monto")));                 
                    model.addRow(registros);                                                                 
                }                
                model.fireTableDataChanged();                                
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "");
        } 
       //view.setEnabled(false);
    }
    
    void abrirventa(){
    buscarventas p;
        menu mimenu;
        mimenu = new menu(0);
        p = new buscarventas(mimenu, true);
        p.setVisible(true);        
        DecimalFormat formateador = new DecimalFormat("###,###");
        
        if(p.codid!=null){
            try{
            String aux;
            codigoventa=p.codid;
            aux = p.codid;
            Number monto1 = formateador.parse(p.montofactura);
            Number monto2 = formateador.parse(p.saldo);
            nrofactura.setText(p.fcliente);
            //montofactura.setText(formateador.format(monto1));
            saldo.setText(formateador.format(monto2));
            saldoFijo =formateador.format(monto2);
            pagar.requestFocus();
            pagar.selectAll();
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);
            }  
            
            //cargarprov(aux);
    }
}
    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void nrofacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrofacturaActionPerformed
        nrofactura.transferFocus();
    }//GEN-LAST:event_nrofacturaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar1ActionPerformed
        abrirventa();
    }//GEN-LAST:event_btncancelar1ActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagarActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void pagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagarKeyReleased
        DecimalFormat formateador = new DecimalFormat("###,###");
        String aux;        
        Integer monto1, monto2, monto3=0, monto4=0, monto5=0;
        try {
            aux = pagar.getText();
            Number c = formateador.parse(aux);
            monto4 = c.intValue();
            pagar.setText(formateador.format(monto4));
            System.out.print(saldoFijo);
            System.out.print("    ESTE ES EL SALDO FIJO   ");
            Number d = formateador.parse(saldoFijo); 
            monto5 = d.intValue();
//            Number a = formateador.parse(saldo.getText());
//            monto1 = a.intValue();
//            Number b = formateador.parse(pagar.getText());
//            monto2 = b.intValue();
//            Number d = formateador.parse(saldoFijo);
//            monto5 = d.intValue();
//            System.out.print("    el  1   ");
//            //monto2=monto2+1;
            if(monto4>monto5){
                JOptionPane.showMessageDialog(null, "El pago debe ser menor o igual al saldo."); 
                pagar.setText("0");
            }
            
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);                
        }   
    }//GEN-LAST:event_pagarKeyReleased

    private void descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripActionPerformed

    private void descripKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_descripKeyReleased

    private void pagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagarKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_pagarKeyTyped

    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        String sql="", sql1="";
        DecimalFormat formateador = new DecimalFormat("###,###");
        String aux, aux1;
        Integer monto4=0, monto5=0;
        try {
            aux = pagar.getText();
            Number c = formateador.parse(aux);
            monto4 = c.intValue();
            aux1 = saldo.getText();
            Number d = formateador.parse(aux1);
            monto5 = d.intValue();
            
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(vuelto.class.getName()).log(Level.SEVERE, null, ex);                
        }     
        sql ="UPDATE pago SET fecha='"+calendar.getDate()+"', retraso='0', monto='"+monto4+"', saldo='"+monto5+"', descripcion='"+descrip.getText()+"' where idpago='"+cod.getText()+"'";         
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        try{        
                PreparedStatement st = cn.prepareStatement(sql);         
                st.executeUpdate();
                System.out.print(sql);
                //bloquear();        
                String valor="";                 
                if(st.executeUpdate()>0){
                    sql1 ="UPDATE extracto SET activo='"+monto4+"', saldo='"+monto5+"', desripcion='"+descrip.getText()+"',fecha='"+calendar.getDate()+"' where activo>0 and idaux='"+cod.getText()+"'";         
                    PreparedStatement st1 = cn.prepareStatement(sql1);         
                    st1.executeUpdate();
                    System.out.print(sql1);
                    if(st1.executeUpdate()>0){
                        cargarpago("");
                        JOptionPane.showMessageDialog(null, "Se actualizó correctamente el Registro.");
                        bloquear();
                    }                                                           
                }        
        }catch(SQLException ex){
                            JOptionPane.showMessageDialog(null, "");
        } 
    }//GEN-LAST:event_btnguardar1ActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        desbloquear();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new cargarprov().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar1;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JButton btnmodificar;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField descrip;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField nrofactura;
    private javax.swing.JTextField pagar;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
