/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;

import claseConectar.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class updateprov extends JDialog {

    /**
     * Creates new form updateprov
     */
    DefaultTableModel modeloRefresca;
    private String codid;
    public updateprov(menu menuprincipal, boolean modal, Integer band, String codigo) {
        super(menuprincipal, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cod.setEnabled(false);
        limpiar();  
        bloquear();
        this.codid = codigo;     
        nombre.setDocument(new solomayusculas());
        direccion.setDocument(new solomayusculas());
        cargar(codigo);
         this.setTitle("Proveedor Seleccionado");
    }
    void limpiar(){
        nombre.setText("");
        ruc.setText("");
        telefono.setText("");          
        direccion.setText("");
    }
    void bloquear(){
        nombre.setEnabled(false);
        ruc.setEnabled(false);
        telefono.setEnabled(false);          
        direccion.setEnabled(false);
        estado.setEnabled(false);
        btnguardar.setEnabled(false);
    }
    void desbloquear(){
        nombre.setEnabled(true);
        ruc.setEnabled(true);
        telefono.setEnabled(true);          
        direccion.setEnabled(true);
        estado.setEnabled(true);
        btnguardar.setEnabled(true);
    }
    void cargar(String valor){
        String [] titulos ={"Cod","Nombre","Ruc","Telefono", "Direccion"};
        String [] registros = new String[6];
        String sql;
        sql="SELECT * FROM proveedor where codprov='"+valor+"'";
        conectar cc = new conectar();
        Connection cn = cc.conexion(); 
        try{
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    cod.setText(rs.getString("codprov"));
                    nombre.setText(rs.getString("nombre"));
                    ruc.setText(rs.getString("ruc"));
                    telefono.setText(rs.getString("telefono"));        
                    direccion.setText(rs.getString("direccion"));
                    estado.setSelectedItem(rs.getString("bloqueo"));                                                                                
                }
        cn.close();
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "");
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ruc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 30));

        jLabel2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("COD.:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, 30));

        ruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rucActionPerformed(evt);
            }
        });
        getContentPane().add(ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 260, 30));

        jLabel4.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("RUC:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("TELEFONO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, -1));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 260, 30));

        jLabel6.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("DIRECCION:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, -1));

        jLabel1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("ESTADO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, -1));

        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Baja"}));
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 260, 30));

        btnguardar.setBackground(new java.awt.Color(0, 102, 153));
        btnguardar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(240, 240, 240));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save3.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 130, 40));

        btnmodificar.setBackground(new java.awt.Color(0, 102, 153));
        btnmodificar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(240, 240, 240));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menusys.png"))); // NOI18N
        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        nombre.transferFocus();
    }//GEN-LAST:event_nombreActionPerformed

    private void rucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rucActionPerformed
        ruc.transferFocus();
    }//GEN-LAST:event_rucActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        telefono.transferFocus();
    }//GEN-LAST:event_telefonoActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        direccion.transferFocus();
    }//GEN-LAST:event_direccionActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        estado.transferFocus();
    }//GEN-LAST:event_estadoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        String sqlcompa, sqlcompa1;
       Integer bandera=0;
       String nomproducto="", nomproducto1="";
        //Integer contador=0, sumacompra=0, sumaventa=0, aux1=0,aux2=0;
//        if(valor.equals("")){
//            sql="SELECT * FROM producto ORDER BY codprodu";
//            System.out.print("entra en el simple");
//        }else{
            sqlcompa="SELECT * FROM proveedor";
            System.out.print("entra en el segundo");
//        }                
//        model = new DefaultTableModel (null, titulos);        
        try{
                conectar cc = new conectar();
                Connection cn = cc.conexion(); 
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sqlcompa);
                System.out.print(sqlcompa);
                //DecimalFormat formateador = new DecimalFormat("###,###");
                while(rs.next()){
                    //sqlcompa1="SELECT * FROM marca where id_marca='"+rs.getString("marca")+"'";
                    //st = cn.createStatement();
                    //ResultSet bs = st.executeQuery(sqlcompa1);
                    //while(bs.next()){
                        nomproducto =rs.getString("nombre").toUpperCase();
                        System.out.print("       LA PRIMERA CADENA      ");
                        System.out.print(nomproducto);
                    //}                   
                    //System.out.print("       LA segunda CADENA      ");
                    //nomproducto1=nombre.getText()+' '+marca.getSelectedItem().toString();
                    if(nomproducto.equals(nombre.getText().toUpperCase())){
                        System.out.print("       LA segunda CADENA      ");
                        System.out.print(nombre.getText());
                        bandera=bandera+1;
                    }
                }
                cn.close();
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "");
        }    
        if(bandera<2){
        

                    //menu m = new menu();
                    //proveedor p = new proveedor(m, false);
                    String sql="";
                    sql ="UPDATE proveedor SET nombre='"+nombre.getText()+"', ruc='"+ruc.getText()+"', telefono='"+telefono.getText()+"', direccion='"+direccion.getText()+"', bloqueo='"+estado.getSelectedItem()+"' where codprov='"+cod.getText()+"'";         
                    conectar cc = new conectar();
                    Connection cn = cc.conexion();
                    try{        
                    PreparedStatement st = cn.prepareStatement(sql);         
                    st.executeUpdate();
                    System.out.print(sql);
                    bloquear();        
                    String valor="";                 
                    if(st.executeUpdate()>0){
                        JOptionPane.showMessageDialog(null, "Se actualizó correctamente el Registro.");                                       
                    }        
                    btnmodificar.setEnabled(true);
                    st.close();  
                    //cn.close();
                    }catch(SQLException ex){            
                    }
                    String [] titulos ={"Cod","Nombre","Ruc","Telefono", "Direccion"};
                    String [] registros = new String[5];
                    String sql1;        
                    sql1="SELECT * FROM proveedor ORDER BY codprov";
                    System.out.print("entra en el simple"); 

                    modeloRefresca = new DefaultTableModel (null, titulos);           
                    try{

                            Statement st = cn.createStatement();
                            ResultSet rs = st.executeQuery(sql1);
                            while(rs.next()){
                                registros[0] = rs.getString("codprov");
                                registros[1] = rs.getString("nombre");
                                registros[2] = rs.getString("ruc");
                                registros[3] = rs.getString("telefono");        
                                registros[4] = rs.getString("direccion");                 
                                modeloRefresca.addRow(registros);                    
                                //JTableHeader header = tablausu.getTableHeader();

                                //header.setForeground(Color.yellow);
                            }                 
                            menu m = new menu(0);
                            //proveedor p = new proveedor(m, true);
                            //p.tablaproveedor.setModel(modeloRefresca);
                            modeloRefresca.fireTableDataChanged();
                    cn.close();
                    }catch(SQLException ex){
                                    JOptionPane.showMessageDialog(null, "");
                    } 
                    this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Este mismo nombre de cliente ya se encuentra registrado.");
        }            
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        desbloquear();
        nombre.requestFocus();
        btnmodificar.setEnabled(false);
        btnguardar.setEnabled(true);
        this.setTitle("Editar Proveedor");
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new updateprov().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField direccion;
    private javax.swing.JComboBox estado;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField ruc;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
