/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventcontrol;

import claseConectar.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author Usuario
 */
    public class updatevende extends JDialog {

    /**
     * Creates new form cargarprov
     */
    Integer ban;    
    DefaultTableModel model;
    DefaultTableModel modeloRefresca;
    Integer banlim=0;
    Integer bandescu=0;
    public updatevende(menu menuprincipal, boolean modal, Integer band, String codigo) {
        super(menuprincipal, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cod.setEnabled(false);                        
        this.setTitle("Vendedor.");  
        cargar(codigo);
        bloquear();
        nece1.setVisible(false);
        nece2.setVisible(false);
        nece3.setVisible(false);
        nece4.setVisible(false);
        nece5.setVisible(false);
    }    
    void limpiar(){
        nombre.setText(null);
        apellido.setText(null);
        ci.setText(null);         
        cod.setText("");
        comision.setText("");
        telefono.setText("");
        salario.setText("");
        obs.setText("");        
    }
    void bloquear(){
        nombre.setEnabled(false);
        apellido.setEnabled(false);
        ci.setEnabled(false);         
        comision.setEnabled(false);
        telefono.setEnabled(false);
        salario.setEnabled(false);
        obs.setEnabled(false);     
        comboestado.setEnabled(false);
        btnguardar.setEnabled(false);
    }
    void desbloquear(){
        nombre.setEnabled(true);
        apellido.setEnabled(true);
        ci.setEnabled(true);  
        comision.setEnabled(true);
        telefono.setEnabled(true);
        salario.setEnabled(true);
        obs.setEnabled(true);   
        comboestado.setEnabled(true);
        btnguardar.setEnabled(true);
    }
    public void setModel(DefaultTableModel modelo){
        modelo = modeloRefresca;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ci = new javax.swing.JTextField();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        obs = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nece1 = new javax.swing.JLabel();
        nece2 = new javax.swing.JLabel();
        nece3 = new javax.swing.JLabel();
        nece4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        telefono1 = new javax.swing.JTextField();
        comboestado = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        comision = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        nece5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                // Forzamos un repintado apenas la ventana termina de abrirse: en algunos
                // entornos (drivers de video/D3D en Windows) el primer pintado de los
                // componentes estilizados no se completa hasta que ocurre un repintado
                // adicional, y esto evita depender de que el usuario pase el mouse encima.
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        getContentPane().repaint();
                    }
                });
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("COD.:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 30));

        jLabel3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 350, 30));

        jLabel4.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("APELLIDO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 350, 30));

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("TELEFONO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, -1));

        ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciActionPerformed(evt);
            }
        });
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 130, 30));

        btnmodificar.setBackground(new java.awt.Color(0, 102, 153));
        btnmodificar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(240, 240, 240));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 130, 40));

        btnguardar.setBackground(new java.awt.Color(0, 102, 153));
        btnguardar.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(240, 240, 240));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save3.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 120, 40));

        obs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obsActionPerformed(evt);
            }
        });
        getContentPane().add(obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 350, 30));

        jLabel10.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("ESTADO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 60, 30));

        salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioActionPerformed(evt);
            }
        });
        salario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salarioKeyTyped(evt);
            }
        });
        getContentPane().add(salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, 30));

        jLabel12.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("SALARIO:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        nece1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        nece1.setForeground(new java.awt.Color(204, 0, 0));
        nece1.setText("CARGAR LOS DATOS REQUERIDOS.");
        getContentPane().add(nece1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        nece2.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        nece2.setForeground(new java.awt.Color(204, 0, 0));
        nece2.setText("*");
        getContentPane().add(nece2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 20, 30));

        nece3.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        nece3.setForeground(new java.awt.Color(204, 0, 0));
        nece3.setText("*");
        getContentPane().add(nece3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 20, 30));

        nece4.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        nece4.setForeground(new java.awt.Color(204, 0, 0));
        nece4.setText("*");
        getContentPane().add(nece4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 20, 30));

        jLabel11.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("CI:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, -1));

        telefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono1ActionPerformed(evt);
            }
        });
        getContentPane().add(telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 130, 30));

        comboestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activado", "Desactivado"}));
        getContentPane().add(comboestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 130, 30));

        jLabel13.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("OBS.:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 70, -1));

        comision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comisionActionPerformed(evt);
            }
        });
        comision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comisionKeyTyped(evt);
            }
        });
        getContentPane().add(comision, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, 30));

        jLabel14.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("COMISION:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 350, 30));

        nece5.setFont(new java.awt.Font("Khmer UI", 1, 18)); // NOI18N
        nece5.setForeground(new java.awt.Color(204, 0, 0));
        nece5.setText("*");
        getContentPane().add(nece5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 20, 30));

        jLabel15.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("%");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 440));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menusys.png"))); // NOI18N
        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    void cargar(String valor){
        String [] titulos ={"Cod","Nombre","Ci","Telefono", "Comision"};
        String [] registros = new String[9];
        String sql;
        sql="SELECT * FROM vendedor where id='"+valor+"'";
        conectar cc = new conectar();
        Connection cn = cc.conexion(); 
        String sex="";
        String iva="";
        String idstring="";
        Integer idtipo;
        try{
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    cod.setText(rs.getString("id"));
                    nombre.setText(rs.getString("nombre"));
                    apellido.setText(rs.getString("apellido"));
                    ci.setText(rs.getString("ci"));                            
                    comboestado.setSelectedItem(rs.getString("bloqueo"));                                                                                
                    telefono.setText(rs.getString("telefono"));
                    salario.setText(rs.getString("salario"));
                    obs.setText(rs.getString("observaciones"));           
                    comision.setText(rs.getString("porciento"));
                }                
                Double aux1=0.0, aux2=0.0;
                aux1 = Double.parseDouble(comision.getText())*100;
                comision.setText(aux1.toString());                                              
        }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "hola");
        } 
    }
    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        desbloquear();
        nombre.requestFocus();
        btnmodificar.setEnabled(false);
        this.setTitle("Editar Vendedor");
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        System.out.print("valor bandera");
        System.out.print(ban);
        String sql="";       
        Integer idusu;
        Integer idrol;
        String sex="";                    
                    Double des=0.0;
                    des = Double.parseDouble(comision.getText())/100;      
                    try{          
                        System.out.print(ban);
                                System.out.print(ban);
                                conectar cc = new conectar();
                                Connection cn = cc.conexion(); 
                                Integer a =1;
                                Double b =1.0;
                                Integer tipo=1;
                                sql ="UPDATE vendedor SET nombre='"+nombre.getText()+"', apellido='"+apellido.getText()+"', ci='"+ci.getText()+"', bloqueo='"+comboestado.getSelectedItem()+"', porciento='"+des.toString()+"', telefono='"+telefono.getText()+"', salario='"+salario.getText()+"', observaciones='"+obs.getText()+"' where id='"+cod.getText()+"'";
                                PreparedStatement st = cn.prepareStatement(sql);                             
                                System.out.print(sql);
                                System.out.print(st);     
                                String valor="";
              
                                if(st.executeUpdate()>0){
                                        JOptionPane.showMessageDialog(null, "Se creó correctamente el Registro.");                               
                                }                    
                
                                st.close();                        
                                this.dispose();
                                System.out.print("PUTO");
                    }catch(SQLException ex){            
                    }
                    String [] titulos ={"Cod","Nombre","Ci","Telefono", "Comision", "Salario"};
                    String [] registros = new String[6];
                    String sql1;       
                    sql1="SELECT * FROM vendedor ORDER BY id";
                    System.out.print("entra en el simple"); 

                    modeloRefresca = new DefaultTableModel (null, titulos);         
                    try{                
                            conectar cc = new conectar();
                            Connection cn = cc.conexion();
                            Statement st = cn.createStatement();
                            ResultSet rs = st.executeQuery(sql1);
                            while(rs.next()){
                                registros[0] = rs.getString("id");
                                registros[1] = rs.getString("nombre")+(" ")+rs.getString("apellido");
                                registros[2] = rs.getString("ci");
                                registros[3] = rs.getString("telefono");        
                                registros[4] = rs.getString("porciento");                 
                                registros[5] = rs.getString("salario");                   
                                modeloRefresca.addRow(registros);                    
            //                    JTableHeader header = tablausu.getTableHeader();
            //
            //                    header.setForeground(Color.yellow);
                            }                 
//                            menu m = new menu();
//                            proveedor p = new proveedor(m, true);
//                            p.tablaproveedor.setModel(modeloRefresca);
                            modeloRefresca.fireTableDataChanged();

                    }catch(SQLException ex){
                                    JOptionPane.showMessageDialog(null, "");
                    }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        nombre.transferFocus();
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        apellido.transferFocus();
    }//GEN-LAST:event_apellidoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void obsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obsActionPerformed

    private void salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioActionPerformed

    private void telefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono1ActionPerformed

    private void ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciActionPerformed
        ci.transferFocus();
    }//GEN-LAST:event_ciActionPerformed

    private void comisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comisionActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void comisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comisionKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_comisionKeyTyped

    private void salarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salarioKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar())
        {
            b=1;
        }
        }
        if(b==0){
            evt.consume();
            getToolkit().beep();             
        }
    }//GEN-LAST:event_salarioKeyTyped

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarprov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new cargarprov().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField cod;
    private javax.swing.JComboBox comboestado;
    private javax.swing.JTextField comision;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel nece1;
    private javax.swing.JLabel nece2;
    private javax.swing.JLabel nece3;
    private javax.swing.JLabel nece4;
    private javax.swing.JLabel nece5;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField obs;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField telefono1;
    // End of variables declaration//GEN-END:variables
}
